run:
  timeout: 5m
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt
    - misspell
    - goconst
    - unconvert
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/scttfrdmn/aws-slurm-burst
  gosec:
    excludes:
      - G204 # Subprocess launched with variable

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
    - path: test/
      linters:
        - gosec